#!/usr/bin/env ruby
require 'httparty'
require 'dotenv/load'
require 'thor'
require 'benchmark'
lib_files = File.join(File.dirname(__FILE__), 'lib', '*.rb')
src_files = File.join(File.dirname(__FILE__), 'src', '**', '*.rb')
Dir[lib_files].sort.each { |file| require file }
Dir[src_files].sort.each { |file| require file }

# The CLI application
class Aoc < Thor
  desc 'download YEAR DAY', 'downloads an input file'
  method_option :download, aliases: '-d'
  def download(year, day)
    PuzzleInput.download(year, day)
  end

  desc 'bootstrap YEAR DAY', 'prepares a sample project for a given day:
downloads the input, creates a sample source and spec file'
  method_option :bootstrap, aliases: '-b'
  def bootstrap(year, day)
    ::PuzzleInput.download(year, day)
    Template.create_templates(year, day)
    puts "https://adventofcode.com/#{year}/day/#{day}"
  end

  desc 'run YEAR DAY', 'executes a given day/year'
  method_option :run_day, aliases: '-r'
  def run_day(year, day)
    puzzle = PuzzleSource.create_puzzle(year, day)
    PuzzleSource.run_part('part 1') { puzzle.part1 }
    PuzzleSource.run_part('part 2') { puzzle.part2 }
  end

  desc 'test YEAR DAY', 'tests a given day/year'
  method_option :test, aliases: '-r'
  def test(year, day)
    padded_day = Day.pad(day)
    system("rspec spec/year#{year}/day#{padded_day}_spec.rb")
  end

  desc 'part1 YEAR DAY', 'executes the part1 for a given day/year'
  method_option :part1
  def part1(year, day)
    puzzle = PuzzleSource.create_puzzle(year, day)
    PuzzleSource.run_part('part 1') { puzzle.part1 }
  end

  desc 'test1 YEAR DAY', 'tests the part1 for a given day/year'
  method_option :test1
  def test1(year, day)
    padded_day = Day.pad(day)
    system("rspec spec/year#{year}/day#{padded_day}_spec.rb" ' --tag part1')
  end

  desc 'part2 YEAR DAY', 'executes the part2 for a given day/year'
  method_option :part2
  def part2(year, day)
    puzzle = PuzzleSource.create_puzzle(year, day)
    PuzzleSource.run_part('part 2') { puzzle.part2 }
  end

  desc 'test2 YEAR DAY', 'tests the part2 for a given day/year'
  method_option :test2
  def test2(year, day)
    padded_day = Day.pad(day)
    system("rspec spec/year#{year}/day#{padded_day}_spec.rb --tag part2")
  end
end

Dotenv.require_keys('AOC_COOKIE', 'AOC_INPUT_DIRECTORY')
Aoc.start
